name: hosvi.app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  csv: ^6.0.0
  flutter_tts: ^3.8.0
  vibration: ^3.1.4
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  # FASE 2
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.0  # (para botón “Cómo llegar”, opcional)
  # HASTA ACA
  #OJITO A LO QUE SE VIENE CON LAS RUTAS
  http: ^1.2.2
  flutter_polyline_points: ^2.0.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/puntos_sample.csv
    - assets/data/puntos_full_normalized.csv
    - assets/data/puntos_full_normalized_arreglado.csv
    - assets/data/puntos_hospitales.csv
    - assets/data/zones.json
